# 데이터베이스 설정
database:
  type: json # 사용할 데이터베이스 타입 (json, mysql, sqlite 중 선택)
  mysql:
    host: "localhost" # MySQL 호스트
    port: 3306 # MySQL 포트
    database: "minecraft" # MySQL 데이터베이스 이름
    username: "root" # MySQL 사용자 이름
    password: "password" # MySQL 비밀번호
  sqlite:
    file: "data.sqlite" # SQLite 파일 경로

# 사용할 수 있는 월드 설정
buildzone:
  restrict_farming_outside: true # 건차 외부에서 농사를 금지할지 여부
  allowed_worlds: # 건차를 사용할 수 있는 월드 목록
    - world
    - world_nether
    - world_the_end
  default_size: 50 # 기본 건축 구역 크기 (x, z)
  default_height: 30 # 기본 건축 구역 높이 (y)
  border_block: "BEDROCK" # 경계 블록 타입
  item:
    material: "STICK" # 건차 아이템의 재료
    name: "건차 아이템" # 건차 아이템의 이름
  farm_items: # 농사 관련 블록 목록
    - WHEAT
    - CARROTS
    - POTATOES
    - BEETROOTS
    - PUMPKIN_STEM
    - MELON_STEM
    - COCOA
    - SUGAR_CANE
    - CACTUS
    - BAMBOO
    - SWEET_BERRY_BUSH
    - NETHER_WART
    - KELP
    - KELP_PLANT
    - SEAGRASS
    - TALL_SEAGRASS
    - SEA_PICKLE
    - TWISTING_VINES
    - WEEPING_VINES
    - CRIMSON_FUNGUS
    - WARPED_FUNGUS
    - CRIMSON_ROOTS
    - WARPED_ROOTS
    - HUGE_MUSHROOM_STEM
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - BROWN_MUSHROOM_BLOCK
    - RED_MUSHROOM_BLOCK
    - CHORUS_FLOWER
    - CHORUS_PLANT
    - SUNFLOWER
    - LILAC
    - ROSE_BUSH
    - PEONY
    - TALL_GRASS
    - LARGE_FERN
    - GRASS
    - FERN
    - DEAD_BUSH
    - VINE
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DARK_OAK_SAPLING

# GUI 설정
menu:
  title: "건차 관리" # GUI 제목
  size: 9 # GUI 크기 (9, 18, 27, 36, 45, 54 중 선택)
  items:
    give_permission:
      material: "DIAMOND" # 권한 주기 아이템 재료
      name: "권한 주기" # 권한 주기 아이템 이름
      slot: 0 # 권한 주기 아이템 위치
    remove_permission:
      material: "IRON_INGOT" # 권한 뺏기 아이템 재료
      name: "권한 뺏기" # 권한 뺏기 아이템 이름
      slot: 1 # 권한 뺏기 아이템 위치
    delete_zone:
      material: "BARRIER" # 건차 삭제 아이템 재료
      name: "건차 삭제" # 건차 삭제 아이템 이름
      slot: 8 # 건차 삭제 아이템 위치

# 메시지 설정
messages:
  zone_not_allowed: "이 월드에서는 건차를 사용할 수 없습니다." # 사용 불가 월드 메시지
  cannot_farm: "건차 외부에서는 농사할 수 없습니다." # 농사 제한 메시지
  no_block_permission: "이 블럭을 파괴할 권한이 없습니다." # 파괴 권한 없음 메시지
  cannot_break: "이 블럭은 부술 수 없습니다." # 블록 파괴 불가 메시지
  zone_created: "건차 구역이 성공적으로 생성되었습니다." # 구역 생성 성공 메시지
  zone_deleted: "건차 구역이 삭제되었습니다." # 구역 삭제 메시지
  zone_overlap: "건차 구역이 다른 구역과 겹칩니다." # 구역 겹침 메시지
  permission_granted: "{player}에게 관리자 권한을 부여했습니다." # 권한 부여 메시지
  permission_revoked: "{player}의 관리자 권한을 제거했습니다." # 권한 제거 메시지
  enter_give_permission: "관리자 권한을 줄 플레이어의 닉네임을 입력하세요 (30초 제한)." # 권한 부여 입력 메시지
  enter_remove_permission: "관리자 권한을 뺏을 플레이어의 닉네임을 입력하세요 (30초 제한)." # 권한 제거 입력 메시지
  permission_timeout: "시간 초과되었습니다." # 시간 초과 메시지
  player_not_found: "플레이어를 찾을 수 없습니다." # 플레이어 찾기 실패 메시지
  no_zone_to_delete: "삭제할 건차 구역이 없습니다." # 삭제할 구역 없음 메시지
  no_permission: "당신은 관리자 권한이 없습니다." # 권한 없음 메시지
  cannot_farm_outside: "건차 구역 외부에서는 농사를 지을 수 없습니다." # 건차구역외 농사 가능 여부
